In [ ]:
#Question 1
mat1.data &lt;- c(7,9,12,2,4,13)
mat1 &lt;- matrix(mat1.data,nrow=2,ncol=3,byrow=TRUE)
mat1
mat2.data &lt;- c(1,7,12,19,2,8,13,20,3,9,14,21)
mat2 &lt;- matrix(mat2.data,nrow=3,ncol=4,byrow=TRUE)
mat2
mat1%*%mat2

7 9 12
2 4 13

1 7 12 19
2 8 13 20
3 9 14 21

61 229 369 565
49 163 258 391

In [28]:

#Question 2
#a
id &lt;- c(1,2,3,4,5)
Name &lt;- c(&quot;Peter&quot;, &quot;Amy&quot;, &quot;Ryan&quot;, &quot;Gary&quot;, &quot;Michelle&quot;)
Salary &lt;- c(623.30, 515.20, 611.00, 729.00, 843.25)

df &lt;- data.frame(id, Name, Salary)
print (df)
#add a column
#b
df$department&lt;-c(&quot;IT&quot;,&quot;Finance&quot;,&quot;Computer Science&quot;,&quot;Marketing&quot;,&quot;Data
Analytics&quot;)
print (df)
id Name Salary
1 1 Peter 623.30
2 2 Amy 515.20
3 3 Ryan 611.00
4 4 Gary 729.00
5 5 Michelle 843.25
id Name Salary department
1 1 Peter 623.30 IT
2 2 Amy 515.20 Finance
3 3 Ryan 611.00 Computer Science
4 4 Gary 729.00 Marketing
5 5 Michelle 843.25 Data Analytics

In [29]:

#extracting rows 1,3,5 from columns 2,3
#c
df[c(1,3,5),c(2,3)]

Name Salary
1 Peter 623.30
3 Ryan 611.00
5 Michelle 843.25



#barplot
#d
x&lt;-df[c(1,4,5),&quot;salary&quot;]
x

barplot(x,
names.arg = c(&quot;Peter&quot;,&quot;Gary&quot;,&quot;Michelle&quot;),
main = &quot;Salary&quot;,
xlab = &quot;name&quot;,
ylab = &#39;salary&#39;,
col=&quot;darkred&quot;,
)



#pie chart
#e
a=max(salary)
b=min(salary)
c=median(salary)
salary1&lt;-c(a,b,c)
percentage&lt;-round(100*c(a,b,c)/sum(c(a,b,c)))
pie(salary1,main=&quot;salary&quot;, labels=paste(c(&quot;max&quot;,&quot;min&quot;,&quot;median&quot;),sep=&quot;
&quot;,percentage,&quot;%&quot;))